// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.RobotContainer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.Drivetrain;
import frc.robot.subsystems.Arm;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class TeleOPDrive extends CommandBase {

    /**
     *
     */
    private static final double DRIVE_DEADBAND = 0.1;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
        private final Drivetrain m_drivetrain;
        private Arm m_arm;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


    public TeleOPDrive(Drivetrain subsystem) {


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_drivetrain = subsystem;
        //m_arm = subsystemArm;
        addRequirements(m_drivetrain);
        //addRequirements(m_arm);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        m_arm = RobotContainer.getInstance().m_arm;
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        //Figure out what the controller value is
        XboxController driveController = RobotContainer.getInstance().getDriveController();
        double forward = -driveController.getLeftY();
        double leftward = driveController.getLeftX();
        double turn = -driveController.getRightX();
        double orbit = driveController.getRightTriggerAxis() - driveController.getLeftTriggerAxis();

        forward = MathUtil.applyDeadband(forward, DRIVE_DEADBAND);
        leftward = MathUtil.applyDeadband(leftward, DRIVE_DEADBAND);        
        turn = MathUtil.applyDeadband(turn, DRIVE_DEADBAND);
        orbit = MathUtil.applyDeadband(orbit, DRIVE_DEADBAND);


        Joystick armJoystick = RobotContainer.getInstance().getArmJoystick();
        boolean field_oriented = !driveController.getRightBumper();
    
        SmartDashboard.putBoolean("Field Oriented", field_oriented);

        if(forward != 0.0 || leftward != 0.0 || turn != 0.0){
            Translation2d translation = new Translation2d(forward, leftward);
            double rotation = turn * Math.PI;
            m_drivetrain.drive(translation, rotation, field_oriented);
        }else if(orbit != 0.0){
            m_drivetrain.orbit(orbit);
        }

        double elbowSpeed = armJoystick.getY();
        elbowSpeed = MathUtil.applyDeadband(elbowSpeed, 0.1);
        m_arm.elbowMove(elbowSpeed);

        double wristSpeed = armJoystick.getX();
        wristSpeed = MathUtil.applyDeadband(wristSpeed, 0.1);
        m_arm.wristSpin(wristSpeed);
        
        double shoulderCommand = armJoystick.getThrottle();
        if (shoulderCommand > 0.8){
            m_arm.shoulderForward(true);
        } else if (shoulderCommand < -0.8) {
            m_arm.shoulderForward(false);
        }
    }
       
        
    
    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
