// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.PowerDistribution.ModuleType;
import edu.wpi.first.wpilibj.PowerDistribution;
import edu.wpi.first.wpilibj.motorcontrol.MotorController;
import edu.wpi.first.wpilibj.motorcontrol.PWMSparkMax;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Drivetrain extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private PWMSparkMax fLDrive;
private PWMSparkMax fLRotate;
private PWMSparkMax fRDrive;
private PWMSparkMax fRRotate;
private PWMSparkMax bLDrive;
private PWMSparkMax bLRotate;
private PWMSparkMax bRDrive;
private PWMSparkMax bRRotate;
private PowerDistribution powerDistribution;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public Drivetrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
fLDrive = new PWMSparkMax(0);
 addChild("FLDrive",fLDrive);
 fLDrive.setInverted(false);

fLRotate = new PWMSparkMax(1);
 addChild("FLRotate",fLRotate);
 fLRotate.setInverted(false);

fRDrive = new PWMSparkMax(2);
 addChild("FRDrive",fRDrive);
 fRDrive.setInverted(false);

fRRotate = new PWMSparkMax(3);
 addChild("FRRotate",fRRotate);
 fRRotate.setInverted(false);

bLDrive = new PWMSparkMax(4);
 addChild("BLDrive",bLDrive);
 bLDrive.setInverted(false);

bLRotate = new PWMSparkMax(5);
 addChild("BLRotate",bLRotate);
 bLRotate.setInverted(false);

bRDrive = new PWMSparkMax(6);
 addChild("BRDrive",bRDrive);
 bRDrive.setInverted(false);

bRRotate = new PWMSparkMax(7);
 addChild("BRRotate",bRRotate);
 bRRotate.setInverted(false);

powerDistribution = new PowerDistribution();
 addChild("PowerDistribution",powerDistribution);
 


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

